var DEBUG = false;

var SCREEN_WIDTH = 480;
var SCREEN_HEIGHT = 480;

var PLAYER_SPEED = 200;
var PLAYER_SWING_SWORD_KEY = Phaser.Input.Keyboard.KeyCodes.Z;
var PLAYER_SWORD_LENGTH = 15;

var ENEMY_OFFSET_X = 8;
var ENEMY_OFFSET_Y = 8;
var ENEMY_PATH_TIMER = 10;
var ENEMY_DEATH_TIME = 0.5;

var ENEMY_MIN_SPAWN_TIMER = 0.5;
var ENEMY_MAX_SPAWN_TIMER = 2;
var ENEMY_MAX_DIFFICULTY_SCORE = 1500;

var FAMILY_PANIC_DISTANCE = 60;