 var player;
 var cursors;
 var fireKey;
 var bullets;
 var asteroids;

var SCREEN_HEIGHT = 700;
var SCREEN_WIDTH = 500;

var BACKGROUND_SPEED = 50;

var ASSET_ROOT = "";

var PLAYER_START_X = 200;
var PLAYER_START_Y = 600;
var PLAYER_SPEED = 200;
var PLAYER_BULLET_TIMER = 100;
var PLAYER_HEALTH = 5;
var PLAYER_BLINK_TIMER = 500;
var PLAYER_DAMAGE = 1;

var BULLET_SPEED = 600;
var BULLET_SIZE = 8;

var ASTEROID_SPEED = 100;
var ASTEROID_TIMER = 2000;
var ASTEROID_HEALTH = 10;
var ASTEROID_DAMAGE = 1;