var SCREEN_WIDTH = 480;
var SCREEN_HEIGHT = 480;

var PLAYER_SPEED = 200;
var PLAYER_SWING_SWORD_KEY = Phaser.Input.Keyboard.KeyCodes.Z;

var ENEMY_OFFSET_X = 8;
var ENEMY_OFFSET_Y = 8;
var ENEMY_HEALTH = 3;
var ENEMY_SPAWN_TIMER = 15;
var ENEMY_PATH_TIMER = 10;

var FAMILY_PANIC_DISTANCE = 60;